### ISSUE TITLE
Massive changes "panel/22&24" icons

### ISSUE THREAD

**Issue by algent-al** [bikass/korla#75]
Hi! I see that folders `panel/22` and `panel/24` are removed.
Was this intentionally?

**Comment by bikass** [comment]
Yes, initial idea was to make original panel icons and not to use from Papirus. Because I have no idea how to resize automatically, I left just one size. Then I saw code of .svg files from Papirus and unfortunately I can't do it. 
I have no idea how folder structure should be done. Other themes have different folders for each size...

**Comment by algent-al** [comment]
Apparently the changes of panel icons are visible. In comparison you can see how the panel icons look when i switch from last version of korla to current one.
![new-korla](https://user-images.githubusercontent.com/46356616/80919067-47446000-8d68-11ea-9684-d98f5f93919e.gif)

Honestly I think, old panel icons were better.

**Comment by bikass** [comment]
Budgie is good for testing these things :) No problems on gnome. And wireless icon is old, should be like this:
![Screenshot from 2020-05-03 21-15-08](https://user-images.githubusercontent.com/8824269/80922131-a794cb00-8d83-11ea-90ea-f8cbe87f0678.jpg)
I made all new symbolic icons. And because I have no idea how to make panel and actions icons. I can restore those different sizes of panel icons.

**Comment by bikass** [comment]
And blue download icon changes into some hard drive icon? Should not be like that.

**Comment by algent-al** [comment]
Yes, I also don’t like that icon. I wanted to tell you about it, but this issue is for panel icons, so I withdrew. I'm glad you mentioned that. The "blue download" icon is for "Software Center" in Solus.

**Comment by bikass** [comment]
OK, restored blue icon. Is everything ok with panel? 
BTW do know some scripts for svgs to cleanup, change size, or mabye to make them like actions/panel icons?

**Comment by algent-al** [comment]
Now I am writing from my phone, but before turning off my PC i synced the theme

**Comment by algent-al** [comment]
Sorry, i don't know any script. Most of icons theme developers that I have seen use a lot of PNG files.
Maybe you should take a look at [elementary](https://github.com/elementary/icons). They use only SVG files in their theme.

**Comment by algent-al** [comment]
Forgot to mention that the blue icon is OK.
